### ISSUE TITLE
Falling at the first hurdle :)

### ISSUE THREAD

**Issue by LydiaF** [NerdWalletOSS/apollo-invalidation-policies#19]
Hi there,

This looks like a fantastic extension. I am trying to test it out, and I swopped out my `InMemoryCache` for `InvalidationPolicyCache` like so:

```
// import { InMemoryCache } from '@apollo/client'
import typePolicies from './typePolicies'
import { CachePersistor } from 'apollo3-cache-persist'
import { InvalidationPolicyCache } from 'apollo-invalidation-policies';

const cache = new InvalidationPolicyCache({
  typePolicies,
  invalidationPolicies: { timeToLive: 1000 }
})
```

However, it is throwing the following error:
```
/Users/home1/code/lt/csuite/node_modules/@apollo/client/cache/inmemory/helpers.js:1
import { isReference, isField, DeepMerger, resultKeyNameFromField, shouldInclude, } from "../../utilities/index.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/home1/code/lt/csuite/node_modules/apollo-invalidation-policies/dist/cache/InvalidationPolicyCache.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
^C⏎              
```

I am sorry if this is my fault and I am missing something obvious!

Thanks for reading and making this extension!

Lydia

**Comment by danReynolds** [comment]
Hey @LydiaF ! Thanks for trying it out! Sorry to hear it's not working. It looks like your environment cannot handle the `import` statement, are you doing server side rendering? Depending on your environment, node, browser etc you might not support the import statements. If your environment is not able to support import statements, we've got a PR open against the Apollo Client https://github.com/apollographql/apollo-client/pull/7645 to resolve that issue soon.

**Comment by LydiaF** [comment]
Hey! Yes, we are using Next :) Okay, I will just wait and hope for the best :) Thanks for the quick reply!

**Comment by marcusstenbeck** [comment]
I ran into this with our testing config. Temporarily solving by adding this to `jest.config.js`:
```js
transformIgnorePatterns: ['node_modules/(?!(@apollo/client)/)'],
```

**Comment by danReynolds** [comment]
@LydiaF We just published a new version you can see here https://www.npmjs.com/package/apollo-invalidation-policies that should work. You can see the PR here: https://github.com/NerdWalletOSS/apollo-invalidation-policies/pull/21 and a more permanent solution will be coming when Apollo releases version 3.4.

**Comment by FoodProduct** [comment]
@marcusstenbeck version `1.0.0-beta13` should theoretically fix your issue as well. Please let us know if it doesn't!

**Comment by LydiaF** [comment]
Dear @danReynolds, thank you so much! That was very fast :) It's running now, looking forward to hopefully getting it all up and running.

**Comment by marcusstenbeck** [comment]
@FoodProduct It does fix it. Awesome!
