### ISSUE TITLE
Specify minimum required version of apollo/client

### ISSUE THREAD

**Issue by mauriziocarboni2** [NerdWalletOSS/apollo-invalidation-policies#26]
I discover that the new version of `apollo-invalidation-policies` doesn't work with versions older than `3.1.0` of `@apollo/client`. This is because before that version `maybeDeepFreeze` wasn't exported, and it's used by `CacheResultProcessor`.

I suggest adding in the Readme ( and package.json ) that the minimum required version of `@apollo/client` is `3.1.0`

**Comment by marcusstenbeck** [comment]
`@apollo/client@^3.3.0` is specified in `peerDependencies`, so you should get a warning in your console if you don't have a compatible version of Apollo client installed.

**Comment by mauriziocarboni2** [comment]
Weird, I don't get any warning. I have:
```json
    "@apollo/client": "3.1.0",
    "apollo-invalidation-policies": "1.0.0-beta13",
```
