### ISSUE TITLE
Feature: Support for default timeToLive

### ISSUE THREAD

**Issue by scottgonzalez** [NerdWalletOSS/apollo-invalidation-policies#4]
I would like to have the ability to set a default `timeToLive` for all types. The existing `timeToLive` configuration would override this value. Perhaps setting `null` or `Infinity` would override the default if you wanted to disable `timeToLive` for a specific type, allowing it to live in cache forever, though just setting a very large value would likely be fine for most use cases.

**Comment by danReynolds** [comment]
Interesting idea, usually the TTLs we've used have been specific to certain types. a Global TTL is pretty broad and powerful but I could see the value given that you don't want the cache to ultimately just grow larger and larger over time. Adding an option for it at the top level like:

```
{
  invalidationPolicies: {
    options: {
      timeToLive: 5000,
    },
    policies: {...}
  }
}
```

or something close to that would do the trick I think. I can look into that.
