### ISSUE TITLE
Find cache entries with expired TTL?

### ISSUE THREAD

**Issue by edxv** [NerdWalletOSS/apollo-invalidation-policies#6]
Hi @danReynolds,

Thanks for your work on this library, it looks great! I'm currently experimenting with Apollo Client 3.0 and was wondering if apollo-invalidation-policies might be suitable for my use case.

TL;DR I'm trying to find entries of a certain type in my cache that haven't been queried in over a week, and evict them.

Long story:

I'm building a React Native app, using apollo-cache-persist to save the cache on the device and persist between sessions. I'm trying to stop the size of the cache growing forever by evicting certain parts of it based on some conditions.

For example, I fetch an `Article` from my CMS which gets stored in the cache. I'd like this particular `Article` to be evicted from the cache if it hasn't been queried in over a week. My initial thought was that I could add a `queriedAt` local-only field to `Article`. Each time an `Article` is fetched (from the CMS or from the cache), the `queriedAt` field would update to a timestamp of now. Then each time the app launches, I would query any `Article`s with a `queriedAt` date greater than 1 week ago, and `cache.evict()` them.

My understanding of this library is that `timeToLive` will evict an entry from the cache after the defined time period, but only when that entry is queried? Is there a way to automatically evict all the entries with an expired `timeToLive`? And, in my case, reset the `timeToLive` each time the entry is queried?

Thanks so much!

Ed

**Comment by danReynolds** [comment]
Hey @edxv I through up a PR if you're up for reviewing it and trying that build to see if it meets your needs! https://github.com/NerdWalletOSS/apollo-invalidation-policies/pull/9

**Comment by edxv** [comment]
🔥 thanks! I'll give it a go this week and get back to you.

**Comment by edxv** [comment]
Hey @danReynolds, sorry for the delay in testing this out. I tried it this afternoon and it works perfectly! Thanks so much.

I have a question about `cache.expire()` — would there be a way to pass in some sort of comparison function?

Example:
I have cache entities of type `Article` which I query directly from my CMS. In `invalidationPolicies`, I give `Article` a TTL and a renewal policy. However, `Article`s can also be queried as part of a broader content type, a magazine issue. I attach a local-only field (e.g. `doNotEvict: true`) to `Article`s when I query them as part of a magazine issue. I'd like to be able to evict expired entities only where `doNotEvict` is falsy.

Thanks again.

**Comment by danReynolds** [comment]
> Hey @danReynolds, sorry for the delay in testing this out. I tried it this afternoon and it works perfectly! Thanks so much.
> 
> I have a question about `cache.expire()` — would there be a way to pass in some sort of comparison function?
> 
> Example:
> I have cache entities of type `Article` which I query directly from my CMS. In `invalidationPolicies`, I give `Article` a TTL and a renewal policy. However, `Article`s can also be queried as part of a broader content type, a magazine issue. I attach a local-only field (e.g. `doNotEvict: true`) to `Article`s when I query them as part of a magazine issue. I'd like to be able to evict expired entities only where `doNotEvict` is falsy.
> 
> Thanks again.

So the scenario is that you have an Article type with an access-based renewal policy and at some time later you manually call `cache.expire` in order to remove ones that haven't been accessed in a while and are expired. But certain ones you don't want removed from this process (those with doNotEvict: true) so you want to be able to filter what `cache.expire` would evict?

I think something like conditional eviction with a comparator would be cleanest if it was a feature of the base cache implementation, like if Apollo implemented a `cache.evictIf(comparator)` for example or if you could read all entities and then loop over them and evict them conditionally. This `cache.expire`'s API is really about evicting expired entities, so making that filterable doesn't seem like a clean API there.

Assuming I was correct in assessing your desired behavior, I think then that the cleanest solution for this lib would be to also expose the expired entities with something like `cache.getExpiredEntities()` or something with a better name to that effect, which you could then loop over, read from the cache and conditionally call `evict` on. It straightforward to expose since cache.expire already iterates over them all and returns their expired IDs. Thoughts?

**Comment by edxv** [comment]
Yeah that is exactly it. Exposing `cache.getExpiredEntities()` and letting the user manually evict as you suggest would be ideal in my case!

**Comment by danReynolds** [comment]
Exposing the entities turned out to be a bit more work than expected, I can look into it soon. I merged the associated renewal policy PR in the meantime.

**Comment by edxv** [comment]
Great, thanks Dan!

**Comment by edxv** [comment]
Hey @danReynolds, hope you're well!

Wondering if the work to expose expired entities is still on the roadmap? We'd love to use this library in production in the next couple of months, but we need to be able to protect some expired cache entities from eviction as described in my [previous comment](https://github.com/NerdWalletOSS/apollo-invalidation-policies/issues/6#issuecomment-692776236).

I and a few others on my team would love to help if possible — we can put in a PR for the functionality if you could give us a few pointers?

Thanks,

Ed

**Comment by danReynolds** [comment]
> Hey @danReynolds, hope you're well!
> 
> Wondering if the work to expose expired entities is still on the roadmap? We'd love to use this library in production in the next couple of months, but we need to be able to protect some expired cache entities from eviction as described in my [previous comment](https://github.com/NerdWalletOSS/apollo-invalidation-policies/issues/6#issuecomment-692776236).
> 
> I and a few others on my team would love to help if possible — we can put in a PR for the functionality if you could give us a few pointers?
> 
> Thanks,
> 
> Ed

Hey @edxv ! Thanks for following up, I'll take a quick pass at doing it today, I think it might be pretty quick actually. Otherwise I'll let you know and would welcome contributions!

**Comment by danReynolds** [comment]
@edxv sorry for not getting to this sooner, PR is up! https://github.com/NerdWalletOSS/apollo-invalidation-policies/pull/14 let me know if that meets your needs. Feel free to suggest any changes.

**Comment by edxv** [comment]
Dan, you're a ⭐ ! I'll have a go at integrating this in our project this week and let you know how it goes.
